language: csharp
solution: DateSeqGenerator.sln
install:
  - nuget restore DateSeqGenerator.sln
  - nuget install FAKE -version 4.45.1
  - nuget install xunit.runner.console -version 2.1.0
script:
  - mono /home/travis/build/MNie/DateSeqGenerator/FAKE.4.45.1/tools/FAKE.exe build.fsx 