language: csharp
solution: DateSeqGenerator.sln
install:
  - nuget restore DateSeqGenerator.sln
  - nuget install FAKE
  - nuget install xunit.runner.console
script:
  - mono /home/travis/build/MNie/DateSeqGenerator/FAKE*/tools/FAKE.exe build.fsx 